export const LOAD_DATA_INITIATION = 'SEARCHMOVIESCONTAINER/LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS = 'SEARCHMOVIESCONTAINER/LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'SEARCHMOVIESCONTAINER/LOAD_DATA_FAILURE';
